name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect to EC2
        uses: easingthemes/ssh-deploy@v2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          local-path: .
          remote-path: /path/to/your/app
